# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Check Homebrew
doctor

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install taps
tap homebrew/dupes
tap peco/peco

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion
# Install zsh
install zsh

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
install openssl
link openssl --force
install homebrew/dupes/grep
install homebrew/dupes/openssh 

# Install other useful binaries
install ack
install rename
install tree
install webkit2png
install zopfli
install p7zip
install ssh-copy-id
install cowsay
install sl
install nmap
install htop-osx
install unp
install speedtest_cli
install axel
install python
install python3
install watch
install ffind
install git-cola
install iftop
install qt5
install pyqt5
install tor
install youtube-dl
install git-extras
install pwgen
install archey
install peco

# Remove outdated versions from the cellar
cleanup
